mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep =",")
mydata
install.packages("dplyr")
install.packages("tibble")
install.packages("ggplot2")
library(dplyr)
library(tibble)
library(ggplot2)
summary(mydata)
str(mydata)
sum(is.na(mydata))
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep =",")
mydata
view(mydata)
attach(mydata)
hist(mydata$Account, main = "Histogram of Account", xlab = "Account", col = "blue", border = "black")
hist(mydata$Transportation, main = "Histogram of Transportation", xlab = "Transportation", col = "blue", border = "black")
hist(mydata$Food, main = "Histogram of Food", xlab = "Food", col = "red", border = "blue")
hist(mydata$Shop, main = "Histogram of Shop", xlab = "Food", col = "red", border = "blue")
hist(mydata$OhterCost, main = "Histogram of Other Cost", xlab = "Food", col = "red", border = "blue")
hist(mydata$Total.Cost, main = "Histogram of Total Cost", xlab = "Food", col = "red", border = "blue")
hist(mydata$Previous.Value, main = "Histogram of Previous Value", xlab = "Food", col = "red", border = "blue")
hist(mydata$Previous.Value, main = "Histogram of Loan", xlab = "Food", col = "red", border = "blue")
hist(mydata$Balance, main = "Histogram of Balance", xlab = "Food", col = "red", border = "blue")
plot(mydata$Account, mydata$Transportation,main = "Scatter Plot of Account vs Transportation", xlab = "Account", ylab = "Transportation",col = "blue", pch = 19)
plot(mydata$Account, mydata$Food,main = "Scatter Plot of Account vs Food", xlab = "Account", ylab = "Food",col = "blue", pch = 19)
ggplot(mydata,aes(x=Food,y=Shop,col=Account))+geom_smooth(se=F)
ggplot(mydata,aes(x=Account,y=Total.Cost,col=Account))+geom_smooth(se=F)
ggplot(mydata,aes(x=Account,y=Shop,col=Account))+geom_smooth(se=F)
ggplot(mydata,aes(x=Transportation,y=Total.Cost,col=Account))+geom_smooth(se=F)
ggplot(mydata,aes(x=Total.Cost,y=Transportation,col=Account))+geom_violin(se=F)
ggplot(mydata,aes(x=Total.Cost,y=Food,col=Account))+geom_violin(se=F)
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep = ",")
mydata <- aggregate(mydata$Account, by=list(Category=mydata$Category), FUN=sum)
pie(mydata$Account, labels = mydata$Account, main = "Student Cost Management of Account")
colors <- rainbow(length(mydata$Account))
pie(mydata$Account, labels = mydata$Account, col = colors, main = "Student Cost Management of Account")
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep = ",")
mydata <- aggregate(mydata$Transportation, by=list(Category=mydata$Category), FUN=sum)
pie(mydata$Transportation, labels = mydata$Transportation, main = "Student Cost Management of Transportation")
colors <- rainbow(length(mydata$Transportation))
pie(mydata$Transportation, labels = mydata$Transportation, col = colors, main = "Student Cost of Transportation")
pie(mydata$Account, labels = mydata$Account, col = colors, main = "Student Cost Management of Account")
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep = ",")
mydata <- aggregate(mydata$Food, by=list(Category=mydata$Category), FUN=sum)
pie(mydata$Food, labels = mydata$Food, main = "Student Cost Management of Food")
colors <- rainbow(length(mydata$Food))
pie(mydata$Food, labels = mydata$Food, col = colors, main = "Student Cost of Food")
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep = ",")
mydata <- aggregate(mydata$Shop, by=list(Category=mydata$Category), FUN=sum)
pie(mydata$Shop, labels = mydata$Shop, main = "Student Cost Management of Shop")
colors <- rainbow(length(mydata$Shop))
pie(mydata$Shop, labels = mydata$Shop, col = colors, main = "Student Cost of Food")
mydata <- read.csv("D:/Summer23-24/Data Science[A]/Studentcostmanagement.csv", header = TRUE, sep = ",")
mydata <- aggregate(mydata$OhterCost, by=list(Category=mydata$Category), FUN=sum)
pie(mydata$OhterCost, labels = mydata$OhterCost, main = "Student Cost Management of Other Cost")
colors <- rainbow(length(mydata$OhterCost))
pie(mydata$OhterCost, labels = mydata$OhterCost, col = colors, main = "Student Cost of Other Cost")
